# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagarismChecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_file_name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('random_file_name', models.CharField(max_length=80, unique=True, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='vogonuser',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='vogonuser',
            name='link',
        ),
        migrations.RemoveField(
            model_name='vogonuser',
            name='location',
        ),
    ]
